matrix:
    include:
        - language: java
          jdk: openjdk11
          script:
              - bash scripts/java_run.sh

        - language: haskell
          ghc: "8.2"
          install:
              - echo "Skipping the default install script"
          script:
              - cabal install random
              - bash scripts/haskell_run.sh
